title: Ok Motorcycles
tagline: Motorcycles are OK
description: 'Motorcycles are OK, and you are OK.'
url: 'https://okmotorcycles.com'
baseurl: /
markdown: kramdown
highlighter: pygments
permalink: pretty
author:
  name: Ok Moto
  url: 'https://twitter.com/'
paginate: 5
version: 0.1.0
github:
  repo: 'https://github.com/greyski/ok-motorcycles-website'
