# Site settings
title: OK Motorcycles
description: Motorcycles are OK
image: /images/profile.png
url: https://okmotorcycles.com
author: Grey Skold
lang: en-US

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap